### ISSUE TITLE
Use out deprecated template_file terraform API 

### ISSUE THREAD

**Issue by rfbird** [DDNStorage/exascaler-cloud-terraform#11]
Hey folks,

I'm seeing a crash on OSX due to the use of an old API, see: https://github.com/hashicorp/terraform-provider-template/issues/85

This is unlikely to cause big issues for customers today, but might in the future. It would be good to migrate to the new/preferred API

**Comment by deiter** [comment]
Hello Robert,

Thank you very much for the report!

Please let me fix it.

Thank you!
