### ISSUE TITLE
[v6.2] "The cls.node_count value must be a positive"

### ISSUE THREAD

**Issue by rohitramu** [DDNStorage/exascaler-cloud-terraform#17]
1. The module no longer functions when Terraform variable `var.cls.node_count` is 0.  Is this intentional?  If so, the validation block found [here](https://github.com/DDNStorage/exascaler-cloud-terraform/blob/master/gcp/variable.tf#L803C5-L803C44) likely needs to be modified to something like this (only using `>`, not `>=`):

    ```
    validation {
      condition     = var.cls.node_count > 0
      error_message = "The cls.node_count value must be a positive."
    }
    ```
2. The module incorrectly requires Terraform >= 1.0.0.  The `replace_triggered_by ` meta-argument was introduced in 1.2.0.

**Comment by deiter** [comment]
Fixed in v2.1.8, thank you!
